[mongo]
evabot_string = "mongodb+srv://evaUtkarsh:WiNE8sOH5slpkmAS@cluster0.fyr3c.mongodb.net/RxmDatabase?retryWrites=true&w=majority"
personal_string = "mongodb+srv://crashgamer0122:rvac8cIVa6xLqN9P@camerainput.r1nwdfo.mongodb.net/"